[problem]
name = "KS_Traveling_Wave_Problem"
neq = 2
problem_type = "ks"

[time_parameters]
T = 0.5
dt = 0.05

[discretization]
n_elements = 2
tau = [ 1.0, 1.0,]

[initial_conditions]
u = "traveling_wave_u"
phi = "traveling_wave_phi"

[exact_solutions]
u = "traveling_wave_u"
phi = "traveling_wave_phi"

[exact_solution_derivatives]
u_x = "traveling_wave_u_x"
phi_x = "traveling_wave_phi_x"

[force_functions]
u_f = "zeros"
phi_f = "zeros"

[domain_initial_conditions]

[domain_force_functions]

[physical_parameters.diffusion]
nu = 1.0
mu = 2.0

[physical_parameters.reaction]
a = 0.0
b = 1.0

[physical_parameters.chemotaxis]
chi = "constant"
dchi = "zeros"
